import type { Conditions,MassItem } from '../models/types';
import { DrivePositionDiagram } from './DrivePositionDiagram';
const Num=({label,value,onChange,unit,min}: {label:string;value:number;onChange:(v:number)=>void;unit?:string;min?:number})=><label><span>{label}</span><div className="input-unit"><input type="number" value={value} min={min} onChange={e=>onChange(Number(e.target.value))}/>{unit&&<i>{unit}</i>}</div></label>;
export function InputPanel({value,onChange}:{value:Conditions;onChange:(c:Conditions)=>void}){const patch=(part:keyof Conditions,v:unknown)=>onChange({...value,[part]:v});const layout=(k:keyof Conditions['layout'],v:number)=>patch('layout',{...value.layout,[k]:v});const motion=(k:keyof Conditions['motion'],v:number|string)=>patch('motion',{...value.motion,[k]:v});const drive=(k:keyof Conditions['drive'],v:unknown)=>patch('drive',{...value.drive,[k]:v});const updateMass=(id:string,k:keyof MassItem,v:unknown)=>patch('masses',value.masses.map(m=>m.id===id?{...m,[k]:v}:m));const xyz=(m:MassItem,k:'x'|'y'|'z',v:number)=>updateMass(m.id,'positionMm',{...m.positionMm,[k]:v});
 const orientationHelp=value.orientation==='wall'
  ?{gravity:'重力 −Z ↓（平面図では下向き）',load:'短手方向モーメント荷重がメイン'}
  :value.orientation==='vertical'
   ?{gravity:'重力 −X ←（平面図では左向き）',load:'長手方向モーメント荷重がメイン'}
   :{gravity:'重力 −Y ⊗（平面図の紙面奥）',load:'ラジアル荷重がメイン'};
 return <div className="input-panel"><section><h3>使用姿勢</h3><label><span>姿勢</span><select value={value.orientation} onChange={e=>patch('orientation',e.target.value)}><option value="horizontal">水平使用（ラジアル荷重がメイン）</option><option value="vertical">垂直使用（長手方向モーメント荷重がメイン）</option><option value="wall">壁掛け使用（短手方向モーメント荷重がメイン）</option></select></label><div className="orientation-help"><b>{orientationHelp.load}</b><span>{orientationHelp.gravity}</span></div><p className="orientation-caution">※ 一般的な荷重傾向です。実際の支配荷重は重心位置、駆動位置、加減速度により変化します。</p></section>
 <section><h3>レール・ブロック構成</h3><div className="grid2"><Num label="レール本数" value={value.layout.railCount} min={1} onChange={v=>layout('railCount',Math.min(4,Math.max(1,v)))}/><Num label="各レールブロック数" value={value.layout.blocksPerRail} min={1} onChange={v=>layout('blocksPerRail',Math.min(4,Math.max(1,v)))}/><Num label="RS レールスパン" value={value.layout.railSpanMm} unit="mm" onChange={v=>layout('railSpanMm',v)}/><Num label="BS ブロックスパン" value={value.layout.blockSpanMm} unit="mm" onChange={v=>layout('blockSpanMm',v)}/><Num label="レール長さ" value={value.layout.railLengthMm} unit="mm" onChange={v=>layout('railLengthMm',v)}/><Num label="ストローク ST" value={value.layout.strokeMm} unit="mm" onChange={v=>layout('strokeMm',v)}/></div></section>
 <section><div className="section-title"><h3>搭載物</h3><button onClick={()=>patch('masses',[...value.masses,{id:crypto.randomUUID(),name:`搭載物${value.masses.length+1}`,massKg:10,positionMm:{x:0,y:100,z:0}}])}>＋ 質量を追加</button></div>{value.masses.map((m,i)=><div className="mass-card" key={m.id}><input aria-label="名称" value={m.name} onChange={e=>updateMass(m.id,'name',e.target.value)}/><button className="icon" disabled={value.masses.length===1} onClick={()=>patch('masses',value.masses.filter(x=>x.id!==m.id))}>×</button><div className="grid2"><Num label="質量 m" value={m.massKg} unit="kg" onChange={v=>updateMass(m.id,'massKg',v)}/><Num label="X" value={m.positionMm.x} unit="mm" onChange={v=>xyz(m,'x',v)}/><Num label="Y" value={m.positionMm.y} unit="mm" onChange={v=>xyz(m,'y',v)}/><Num label="Z" value={m.positionMm.z} unit="mm" onChange={v=>xyz(m,'z',v)}/></div></div>)}</section>
 <section><h3>駆動条件</h3><label><span>駆動方式</span><select value={value.drive.type} onChange={e=>drive('type',e.target.value)}><option value="ballscrew">ボールねじ</option><option value="belt">ベルト</option><option value="rack">ラック＆ピニオン</option><option value="linearMotor">リニアモータ</option><option value="other">その他</option></select></label><label><span>駆動力</span><select value={value.drive.mode} onChange={e=>drive('mode',e.target.value)}><option value="automatic">運動条件から自動</option><option value="manual">手動入力</option></select></label>{value.drive.mode==='manual'&&<Num label="駆動力" value={value.drive.forceN} unit="N" onChange={v=>drive('forceN',v)}/>}<div className="grid2"><Num label="駆動X位置" value={value.drive.positionMm.x} unit="mm" onChange={v=>drive('positionMm',{...value.drive.positionMm,x:v})}/><Num label="駆動高さ Br" value={value.drive.positionMm.y} unit="mm" onChange={v=>drive('positionMm',{...value.drive.positionMm,y:v})}/><Num label="駆動横位置 Bt" value={value.drive.positionMm.z} unit="mm" onChange={v=>drive('positionMm',{...value.drive.positionMm,z:v})}/></div><DrivePositionDiagram conditions={value}/></section>
 <section><h3>動作・寿命条件</h3><div className="grid2"><Num label="最高速度 V" value={value.motion.maxSpeedMmS} unit="mm/s" onChange={v=>motion('maxSpeedMmS',v)}/><label><span>加速度設定</span><select value={value.motion.accelMode} onChange={e=>motion('accelMode',e.target.value)}><option value="time">時間から計算</option><option value="direct">直接入力</option></select></label>{value.motion.accelMode==='time'?<><Num label="加速時間 ta" value={value.motion.accelTimeS} unit="s" onChange={v=>motion('accelTimeS',v)}/><Num label="減速時間 td" value={value.motion.decelTimeS} unit="s" onChange={v=>motion('decelTimeS',v)}/></>:<><Num label="加速度" value={value.motion.accelerationMS2} unit="m/s²" onChange={v=>motion('accelerationMS2',v)}/><Num label="減速度" value={value.motion.decelerationMS2} unit="m/s²" onChange={v=>motion('decelerationMS2',v)}/></>}<Num label="往復回数" value={value.motion.cyclesPerMin} unit="/min" onChange={v=>motion('cyclesPerMin',v)}/><Num label="稼働時間" value={value.motion.hoursPerDay} unit="h/day" onChange={v=>motion('hoursPerDay',v)}/><Num label="稼働日数" value={value.motion.daysPerYear} unit="day/year" onChange={v=>motion('daysPerYear',v)}/><Num label="荷重係数 fw" value={value.loadFactor} onChange={v=>patch('loadFactor',v)}/><Num label="要求安全率" value={value.requiredSafety} onChange={v=>patch('requiredSafety',v)}/><Num label="希望寿命" value={value.desiredLifeHours} unit="h" onChange={v=>patch('desiredLifeHours',v)}/></div><p className="hint">fw参考：低速・衝撃小 1.0～1.2／一般 1.2～1.5／高速・振動衝撃あり 1.5～2.5。正式値はメーカー資料を確認してください。</p></section></div>}