import type { CalculationResult,Conditions } from '../models/types';import { createBlockPositions } from '../calculations/blockLoadDistribution';import { fmt,mToMm } from '../utils/unitConversion';
import { OrthographicViews } from './OrthographicViews';
export function LayoutDiagram({conditions,result}:{conditions:Conditions;result:CalculationResult}){const p=createBlockPositions(conditions.layout),max=Math.max(1,...result.phases.flatMap(x=>Object.values(x.loads).map(l=>l.equivalentN)));const worst=result.phases.find(x=>x.phase.label===result.worstPhase);
 // 壁掛け時は、物理的な重力 -Z が画面下を向くよう表示上のZ軸を上下反転する。
 // 計算座標・荷重の符号は変更せず、SVGへの投影だけを変更する。
 const zScreenSign=conditions.orientation==='wall'?-1:1;
 // 左側は座標軸、右側はRS寸法に使いながら、レールをブロック外側まで均等に張り出させる。
 const mechanismCenterX=285,blockSpanPx=170,railStartX=128,railEndX=455,rsDimensionX=475;
 const xMap=(x:number)=>mechanismCenterX+x/Math.max(1,conditions.layout.blockSpanMm)*blockSpanPx,zMap=(z:number)=>155+zScreenSign*z/Math.max(1,conditions.layout.railSpanMm)*180;
 const gravity=conditions.orientation==='wall'
  ?{pose:'壁掛け使用',direction:'−Z方向（平面図では下方向）',axis:'−Z',arrow:'↓',screen:'図の下方向'}
  :conditions.orientation==='vertical'
   ?{pose:'垂直使用',direction:'−X方向（平面図では左方向）',axis:'−X',arrow:'←',screen:'図の左方向'}
   :{pose:'水平使用',direction:'−Y方向（平面図の紙面奥方向）',axis:'−Y',arrow:'⊗',screen:'紙面の奥方向'};
 const zAxisNote=conditions.orientation==='wall'?'画面右＝+X ／ 画面上＝+Z':'画面右＝+X ／ 画面下＝+Z';
 return <div className="diagram"><div className="diagram-heading"><div className="view-title">平面図（X–Z） <span>{zAxisNote}</span></div></div><div className="load-legend"><div><b>表示状態：{result.worstPhase}</b><span>全フェーズ中で最大荷重が発生した状態</span></div><div><b>P [N]：等価荷重</b><span>方向別荷重を寿命・選定用に合成した大きさ（方向なし）</span></div><div><b><i className="meter-sample"/>横棒：相対的な大きさ</b><span>この状態で最も大きいブロックを100%として表示</span></div></div><p className="load-legend-note">実際のラジアル・逆ラジアル・横・軸方向荷重は「荷重結果」タブで確認できます。</p><div className={`gravity-guide ${conditions.orientation}`} role="status" aria-label={`${gravity.pose}。重力は${gravity.direction}`}><span className="gravity-guide-arrow" aria-hidden="true">{gravity.arrow}</span><div><b>{gravity.pose}　重力方向：{gravity.axis}</b><span>{gravity.screen}　／　g = 9.80665 m/s²</span></div></div><svg viewBox="0 0 500 320" role="img" aria-label={`LMガイド平面配置図。${gravity.pose}、重力は${gravity.direction}。座標はX-Z。${result.worstPhase}時の各ブロック等価荷重を表示。`}>
  <defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="4" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8z" fill="currentColor"/></marker><marker id="planAxisArrow" markerWidth="7" markerHeight="7" refX="5" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7z"/></marker></defs>
  <g className="plan-axis" aria-label={conditions.orientation==='wall'?'+Xは右、+Zは上':'+Xは右、+Zは下'}><rect x="10" y="10" width="92" height="76" rx="6"/><text className="axis-title" x="56" y="29" textAnchor="middle">座標 X–Z</text><line x1="49" y1="54" x2="86" y2="54" markerEnd="url(#planAxisArrow)"/><text x="78" y="47">+X</text>{conditions.orientation==='wall'?<><line x1="49" y1="54" x2="49" y2="34" markerEnd="url(#planAxisArrow)"/><text x="55" y="42">+Z</text></>:<><line x1="49" y1="54" x2="49" y2="79" markerEnd="url(#planAxisArrow)"/><text x="55" y="77">+Z</text></>}</g>
  {Array.from({length:conditions.layout.railCount},(_,i)=>{const zMm=conditions.layout.railCount===1?0:-conditions.layout.railSpanMm/2+conditions.layout.railSpanMm*i/(conditions.layout.railCount-1),screenZ=zMap(zMm);return <g key={i}><rect x={railStartX} y={screenZ-6} width={railEndX-railStartX} height="12" rx="5" className="rail"/><text className="rail-label" x={railEndX-4} y={screenZ-12} textAnchor="end">Rail {i+1}</text></g>})}
  {p.map(b=>{const load=worst?.loads[b.id]?.equivalentN??0,ratio=Math.max(0,Math.min(1,load/max)),isWorst=b.id===result.worstBlock;return <g key={b.id} className={isWorst?'block-load worst-load':'block-load'} transform={`translate(${xMap(mToMm(b.xM))},${zMap(mToMm(b.zM))})`}><rect x="-34" y="-23" width="68" height="46" rx="6" className={isWorst?'block worst':'block'}/><text className="block-name" textAnchor="middle" y="-6">{b.id.replace('Block ','B')}</text><text className="block-load-value" textAnchor="middle" y="10">{fmt(load,0)} N</text><rect className="load-meter-track" x="-27" y="16" width="54" height="4" rx="2"/><rect className="load-meter-fill" x="-27" y="16" width={54*ratio} height="4" rx="2"/></g>})}
  <g className="plan-cog" transform={`translate(${xMap(result.cogMm.x)},${zMap(result.cogMm.z)})`}><circle r="11" className="cog"/><path d="M-8 0h16M0-8v16"/><text x="15" y="-12">合成重心</text></g>
  <line x1={xMap(-conditions.layout.blockSpanMm/2)} x2={xMap(conditions.layout.blockSpanMm/2)} y1="305" y2="305" className="dimension bs-dimension" markerStart="url(#arrow)" markerEnd="url(#arrow)"/><g className="dimension-label-box bs-label-box"><rect x={mechanismCenterX-43} y="274" width="86" height="24" rx="4"/><text className="bs-label" x={mechanismCenterX} y="291" textAnchor="middle">BS {fmt(conditions.layout.blockSpanMm,0)} mm</text></g>
  <line x1={rsDimensionX} x2={rsDimensionX} y1={zMap(-conditions.layout.railSpanMm/2)} y2={zMap(conditions.layout.railSpanMm/2)} className="dimension rs-dimension" markerStart="url(#arrow)" markerEnd="url(#arrow)"/><g className="dimension-label-box rs-label-box"><rect x="380" y="143" width="86" height="24" rx="4"/><text className="rs-label" x="423" y="160" textAnchor="middle">RS {fmt(conditions.layout.railSpanMm,0)} mm</text></g>
 </svg><OrthographicViews conditions={conditions} result={result}/></div>}