import { useEffect,useMemo,useRef,useState } from 'react';import type { Conditions,Product,Project } from './models/types';import { defaultConditions } from './models/defaults';import { calculateSystem } from './calculations/calculateSystem';import { calculateTravel } from './calculations/lifeHours';import { selectCandidates } from './productData/selection';import { csvTemplate,parseProductCsv,sampleProducts } from './productData/products';import { deleteProject,exportProject,importProject,listProjects,saveProject } from './storage/database';import { InputPanel } from './components/InputPanel';import { LayoutDiagram } from './components/LayoutDiagram';import { ResultsPanel } from './components/ResultsPanel';import { CalculationBasis,CandidateTable,LifeEvaluation,LoadResults,Optimization,Sensitivity,Verification } from './components/EngineeringViews';
type Tab='条件・配置'|'荷重結果'|'製品選定'|'寿命評価'|'最適化'|'詳細仕様'|'計算根拠';const tabs:Tab[]=['条件・配置','荷重結果','製品選定','寿命評価','最適化','詳細仕様','計算根拠'];
const download=(name:string,text:string,type='application/json')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
export default function App(){const [conditions,setConditions]=useState<Conditions>(defaultConditions),[tab,setTab]=useState<Tab>('条件・配置'),[dark,setDark]=useState(()=>localStorage.getItem('theme')==='dark'),[products,setProducts]=useState<Product[]>(sampleProducts),[projectName,setProjectName]=useState('XYステージ'),[projects,setProjects]=useState<Project[]>([]),[selectedModel,setSelectedModel]=useState(''),file=useRef<HTMLInputElement>(null),csv=useRef<HTMLInputElement>(null);
 const result=useMemo(()=>calculateSystem(conditions),[conditions]),travel=useMemo(()=>calculateTravel(conditions.layout.strokeMm,conditions.motion.cyclesPerMin,conditions.motion.hoursPerDay,conditions.motion.daysPerYear),[conditions]),candidates=useMemo(()=>selectCandidates(products,result,conditions.loadFactor,conditions.requiredSafety,conditions.desiredLifeHours,travel.hourKm),[products,result,conditions,travel.hourKm]);const selected=candidates.find(c=>c.product.model===selectedModel)??candidates[0];
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('theme',dark?'dark':'light')},[dark]);useEffect(()=>{listProjects().then(setProjects).catch(()=>{})},[]);
 const save=async()=>{const p:Project={id:projects.find(x=>x.name===projectName)?.id??crypto.randomUUID(),name:projectName,conditions,selectedModel:selected?.product.model,updatedAt:new Date().toISOString()};await saveProject(p);setProjects(await listProjects())};
 const importJson=async(f:File)=>{try{const p=importProject(await f.text());setConditions(p.conditions);setProjectName(p.name);setSelectedModel(p.selectedModel??'');await saveProject(p);setProjects(await listProjects())}catch(e){alert(e instanceof Error?e.message:'JSONを読み込めません。')}};
 const importCsv=async(f:File)=>{const loaded=parseProductCsv(await f.text());if(!loaded.length)return alert('有効な製品行がありません。C、C0、列名を確認してください。');setProducts([...sampleProducts,...loaded]);};
 return <div className="app"><header><div className="brand"><div className="logo"><img src="/lm-guide-mark.svg" alt="" width="52" height="52"/></div><div><h1>LM Guide Engineering Studio</h1><p>荷重分布・静的安全率・寿命・レイアウト設計支援</p></div></div><div className="project-tools"><input value={projectName} onChange={e=>setProjectName(e.target.value)} aria-label="案件名"/><button onClick={save}>案件保存</button><select aria-label="保存案件" value="" onChange={e=>{const p=projects.find(x=>x.id===e.target.value);if(p){setConditions(p.conditions);setProjectName(p.name);setSelectedModel(p.selectedModel??'')}}}><option value="">保存案件を開く…</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name} — {new Date(p.updatedAt).toLocaleDateString('ja-JP')}</option>)}</select><button title="テーマ切替" onClick={()=>setDark(!dark)}>{dark?'☀':'☾'}</button></div></header>
 <nav>{tabs.map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 <main className={tab==='条件・配置'?'layout-input':'layout-focus'}>{tab==='条件・配置'&&<aside className="left"><InputPanel value={conditions} onChange={setConditions}/><section className="data-tools"><h3>データ入出力</h3><div><button onClick={()=>download(`${projectName}.json`,exportProject({id:crypto.randomUUID(),name:projectName,conditions,selectedModel:selected?.product.model,updatedAt:new Date().toISOString()}))}>案件 JSON Export</button><button onClick={()=>file.current?.click()}>JSON Import</button><input hidden ref={file} type="file" accept=".json" onChange={e=>e.target.files?.[0]&&importJson(e.target.files[0])}/><button onClick={()=>csv.current?.click()}>製品 CSV Import</button><input hidden ref={csv} type="file" accept=".csv" onChange={e=>e.target.files?.[0]&&importCsv(e.target.files[0])}/><button onClick={()=>download('lm-product-template.csv',csvTemplate,'text/csv')}>CSVテンプレート</button></div>{projects.length>0&&<button className="danger" onClick={async()=>{const p=projects.find(x=>x.name===projectName);if(p){await deleteProject(p.id);setProjects(await listProjects())}}}>現在名の保存案件を削除</button>}</section></aside>}
 <section className="workspace"><div className="workspace-head"><div><span className="eyebrow">REAL-TIME ENGINEERING MODEL</span><h2>{tab}</h2></div><div className="status"><span className={result.warnings.length?'warn-dot':'ok-dot'}/>{result.warnings.length} warnings</div></div>
  {tab==='条件・配置'&&<LayoutDiagram conditions={conditions} result={result}/>} {tab==='荷重結果'&&<LoadResults result={result}/>} {tab==='製品選定'&&<><CandidateTable candidates={candidates}/>{selected&&<label className="select-product">比較・詳細対象<select value={selected.product.model} onChange={e=>setSelectedModel(e.target.value)}>{candidates.map(c=><option key={c.product.model}>{c.product.model}</option>)}</select></label>}</>}
  {tab==='寿命評価'&&<LifeEvaluation conditions={conditions} candidate={selected}/>} {tab==='最適化'&&selected&&<><Optimization conditions={conditions} product={selected.product}/><Sensitivity conditions={conditions} product={selected.product}/></>}
  {tab==='詳細仕様'&&selected&&<Details product={selected.product}/>} {tab==='計算根拠'&&<><CalculationBasis conditions={conditions} result={result} candidate={selected}/><Verification conditions={conditions} result={result} candidates={candidates}/></>}
 </section>{tab==='条件・配置'&&<ResultsPanel conditions={conditions} result={result} candidates={candidates}/>}</main><footer>Initial design & parameter study tool — 最終選定はメーカー公式資料で照合してください。</footer></div>}
function Details({product}:{product:Product}){const [env,setEnv]=useState<string[]>(['一般環境']);const environments=['一般環境','粉塵','切粉','液体飛散','クーラント','溶接スパッタ','真空','高温','給脂困難'];const rec:string[]=[];if(env.some(x=>['粉塵','切粉'].includes(x)))rec.push('高防塵シール、スクレーパ、カバーを検討');if(env.some(x=>['液体飛散','クーラント'].includes(x)))rec.push('エンド／サイドシール、耐液潤滑剤をメーカー確認');if(env.includes('溶接スパッタ'))rec.push('金属スクレーパ、伸縮カバーを検討');if(env.includes('給脂困難'))rec.push('集中給脂または潤滑装置を検討');if(env.some(x=>['真空','高温'].includes(x)))rec.push('特殊材質・潤滑剤・使用温度をメーカー確認');return <div className="content-card details"><h2>{product.model} 詳細仕様</h2><p className="sample-banner">データ品質: {product.dataQuality}／出典: {product.dataSource}／確認日: {product.verifiedDate??'未確認'}</p><div className="detail-grid"><label>予圧<select>{product.preloadClasses.map(x=><option key={x}>{x}</option>)}</select><small>予圧荷重データ未登録のため寿命補正なし。メーカー確認が必要です。</small></label><label>精度<select>{product.accuracyGrades.map(x=><option key={x}>{x}</option>)}</select><small>製品マスタ登録済み等級のみ表示。</small></label></div><h3>使用環境</h3><div className="checks">{environments.map(x=><label key={x}><input type="checkbox" checked={env.includes(x)} onChange={()=>setEnv(env.includes(x)?env.filter(y=>y!==x):[...env,x])}/>{x}</label>)}</div><h3>防塵・潤滑の検討項目</h3>{rec.length?rec.map(x=><p key={x}>• {x}</p>):<p>一般的なエンドシールと定期給脂条件を確認してください。</p>}<h3>マスタ登録オプション</h3><p>{product.options.join(' / ')||'登録なし'}</p><div className="links">{product.officialUrl&&<a href={product.officialUrl} target="_blank">公式製品ページ</a>}{product.selectorUrl&&<a href={product.selectorUrl} target="_blank">選定ツール</a>}{product.cadUrl&&<a href={product.cadUrl} target="_blank">CAD</a>}{product.catalogUrl&&<a href={product.catalogUrl} target="_blank">カタログ</a>}</div></div>}